import { TabulatorFull as Tabulator } from 'tabulator-tables';
import 'tabulator-tables/dist/css/tabulator.min.css';

const tableColumns = [
    { title: "Company", field: "company", widthGrow: 2, editor: "input" },
    { title: "Case ID", field: "case_id", widthGrow: 2, editor: "input" },
    { title: "Work Order", field: "work_order", widthGrow: 2, editor: "input" },
    { title: "Material Order (MO No)", field: "material_order_no", widthGrow: 2, editor: "input" },
    { title: "Region", field: "region", widthGrow: 2, editor: "input" },
    { title: "Engineer", field: "engineer", widthGrow: 2, editor: "input" },
    { title: "Case Type", field: "case_type", widthGrow: 2, editor: "input" },
    { title: "Order Type (OTC Code)", field: "order_type_otc_code", widthGrow: 2, editor: "input" },
    { title: "SLA", field: "sla", widthGrow: 2, editor: "input" },
    { title: "Multiple Visit Flag", field: "multiple_visit_flag", widthGrow: 2, editor: "input" },
    { title: "Remark", field: "remark", widthGrow: 2, editor: "input" },
    { title: "Delay Reason (Onsite)", field: "delay_reason_onsite", widthGrow: 2, editor: "input" },
    { title: "Received Date", field: "received_date", widthGrow: 2, editor: "input" },
    { title: "Dispatched Date", field: "dispatched_date", widthGrow: 2, editor: "input" },
    { title: "Response Date", field: "response_date", widthGrow: 2, editor: "input" },
    { title: "MainCase Close Date", field: "maincase_close_date", widthGrow: 2, editor: "input" },
    { title: "Repair Class", field: "repair_class", widthGrow: 2, editor: "input" },
    { title: "Case Status", field: "case_status", widthGrow: 2, editor: "input" },
    { title: "Business Segment", field: "business_segment", widthGrow: 2, editor: "input" },
    { title: "HPI Segment", field: "hpi_segment", widthGrow: 2, editor: "input" },
    { title: "Serial Number", field: "serial_number", widthGrow: 2, editor: "input" },
    { title: "Product No", field: "product_no", widthGrow: 2, editor: "input" },
    { title: "Product Name", field: "product_name", widthGrow: 2, editor: "input" },
    { title: "Product Line", field: "product_line", widthGrow: 2, editor: "input" },
    { title: "Product Category (PL Code)", field: "product_category_pl_code", widthGrow: 2, editor: "input" },
    { title: "Part Number", field: "part_number", widthGrow: 2, editor: "input" },
    { title: "Part Description", field: "part_description", widthGrow: 2, editor: "input" },
    { title: "Onsite Location (City)", field: "onsite_location_city", widthGrow: 2, editor: "input" },
    { title: "Customer", field: "customer", widthGrow: 2, editor: "input" },
    { title: "Zip/Postal Code", field: "zip_postal_code", editor: "input" },
    { title: "Problem (Case Subject)", field: "problem_case_subject", widthGrow: 2, editor: "input" },
    { title: "CDAX WO Status", field: "cdax_wo_status", widthGrow: 2, editor: "input" },
    { title: "CDAX MainCase Status", field: "cdax_maincase_status", editor: "input" },
    { title: "CDAX WorkOrder Finished Date", field: "cdax_workorder_finished_date", widthGrow: 2, editor: "input" },
    { title: "CDAX WorkOrder Close Date", field: "cdax_workorder_close_date", widthGrow: 2, editor: "input" },
    { title: "Repair Class Codes", field: "repair_class_codes", widthGrow: 2, editor: "input" },
    { title: "CDAX MO Status", field: "cdax_mo_status", widthGrow: 2, editor: "input" },
    { title: "CDAX MO Failure Code", field: "cdax_mo_failure_code", widthGrow: 2, editor: "input" },
    { title: "BackOrder ETD", field: "backorder_etd", widthGrow: 2, editor: "input" },
    { title: "ETA Aging", field: "eta_aging", widthGrow: 2, editor: "input" },
    { title: "MO Actual Ship Date", field: "mo_actual_ship_date", widthGrow: 2, editor: "input" },
    { title: "ATP Status (Material Order)", field: "atp_status_material_order", widthGrow: 2, editor: "input" },
    { title: "CDAX WO Count", field: "cdax_wo_count", widthGrow: 2, editor: "input" },
    { title: "Happy Call Activity Status", field: "happy_call_activity_status", widthGrow: 2, editor: "input" },
    { title: "Happy Call Case Status", field: "happy_call_case_status", widthGrow: 2, editor: "input" },
    { title: "Happy Call (DOA)", field: "happy_call_doa", widthGrow: 2, editor: "input" },
    { title: "Happy Call Case Status (DOA)", field: "happy_call_case_status_doa", widthGrow: 2, editor: "input" },
    { title: "MainCase (Open) Owner", field: "maincase_open_owner", widthGrow: 2, editor: "input" },
    { title: "MainCase (Open) Status", field: "maincase_open_status", widthGrow: 2, editor: "input" },
    { title: "MainCase (Closed) Closed Date", field: "maincase_closed_date", widthGrow: 2, editor: "input" },
    { title: "MainCase (Closed) Case Resolution", field: "maincase_closed_case_resolution", widthGrow: 2, editor: "input" },
    { title: "Complaint Count", field: "complaint_count", widthGrow: 2, editor: "input" },
    { title: "CDAX WO Delay Code", field: "cdax_wo_delay_code", widthGrow: 2, editor: "input" },
    { title: "Bookable Resource Booking Status", field: "bookable_resource_booking_status", widthGrow: 2, editor: "input" },
    { title: "Bookable Resource Start Time", field: "bookable_resource_start_time", widthGrow: 2, editor: "input" },
    { title: "SLA Count (Days)", field: "sla_count_days", widthGrow: 2, editor: "input" },
    { title: "1st WO", field: "first_wo", widthGrow: 2, editor: "input" },
    { title: "Aging Bucket (Case Created)", field: "aging_bucket_case_created", widthGrow: 2, editor: "input" },
    { title: "Aging (Case Created)", field: "aging_case_created", widthGrow: 2, editor: "input" },
    { title: "CU Reason Breakdown", field: "cu_reason_breakdown", widthGrow: 2, editor: "input" },
    { title: "Gaming (M5,M7)", field: "gaming_m5_m7", widthGrow: 2, editor: "input" },
    { title: "vlookup MainCase Open (Created On)", field: "vlookup_maincase_open_created_on", widthGrow: 2, editor: "input" },
    { title: "Aging Bucket (Case Received)", field: "aging_bucket_case_received", widthGrow: 2, editor: "input" },
    { title: "Aging (Case Received)", field: "aging_case_received", widthGrow: 2, editor: "input" },
    { title: "Case Delay Dispatched", field: "case_delay_dispatched", widthGrow: 2, editor: "input" },
];

// Initialize Tabulator on #admin-table
document.addEventListener("DOMContentLoaded", () => {
    const table = new Tabulator("#admin-table", {
        height: "auto",
        layout: "fitData", // columns sized to fit header + cell content
        placeholder: "No Data Available",
        columns: tableColumns,
        //enable range selection
        selectableRange: 1,
        selectableRangeColumns: true,
        selectableRangeRows: true,
        selectableRangeClearCells: true,

        //change edit trigger mode to make cell navigation smoother
        editTriggerEvent: "dblclick",

        //configure clipboard to allow copy and paste of range format data
        clipboard: true,
        clipboardCopyStyled: false,
        clipboardCopyConfig: {
            rowHeaders: false,
            columnHeaders: false,
        },
        clipboardCopyRowRange: "range",
        clipboardPasteParser: "range",
        clipboardPasteAction: "range",

        rowHeader: { resizable: false, frozen: true, width: 40, hozAlign: "center", formatter: "rownum", cssClass: "range-header-col", editor: false },

        //setup cells to work as a spreadsheet
        columnDefaults: {
            headerSort: false,
            headerHozAlign: "center",
            editor: "input",
            resizable: "header",
            width: 100,
        },
        editable: true,
        //data: tableData
        ajaxURL: "/admin/data",  // Laravel route
        ajaxResponse: function (url, params, response) {
            return response;     // Tabulator uses this JSON
        }
    });
});

const tableData = [
    {
        company: "PWIT",
        case_id: "5125393699",
        work_order: "WO-025837528",
        material_order_no: "MO-704247464",
        region: "CENTRAL",
        engineer: "Hafiz",
        case_type: "HW Delivery",
        order_type_otc_code: "05K-Extended Warranty",
        sla: "NBD",
        multiple_visit_flag: "8",
        remark: "19/6-ONSITE ... 20/6-JOB DONE ... 12/7-MONITORING UNTIL NEXT FRIDAY 19/7/2024",
        delay_reason_onsite: "Part Availability",
        received_date: "2024-06-07",
        dispatched_date: "2024-06-07",
        response_date: "2024-06-20",
        maincase_close_date: null,
        repair_class: "CO - Rpr,Compt,Parts Repl",
        case_status: "WO Closed",
        business_segment: "Printing",
        hpi_segment: "Commercial",
        serial_number: "MY2383W00D",
        product_no: "2RM82A",
        product_name: "HP DesignJet Z9+ Pro 64-in Printer",
        product_line: "Large Format Design HW",
        product_category_pl_code: "P3000",
        part_number: "2RM82-67051",
        part_description: "Motor mount (with transmission) LN SERV",
        onsite_location_city: "KUALA LUMPUR",
        customer: "FABRIC STRUCTURE",
        zip_postal_code: "53100",
        problem_case_subject: "Take up reel speed issue",
        cdax_wo_status: "Closed - Posted",
        cdax_maincase_status: "#N/A",
        cdax_workorder_finished_date: "2024-06-20",
        cdax_workorder_close_date: "2024-06-20",
        repair_class_codes: "CO - Rpr,Compt,Parts Repl",
        cdax_mo_status: "Closed",
        cdax_mo_failure_code: "73 - Used & Consumed",
        backorder_etd: "2024-06-14",
        eta_aging: "Backordered",
        mo_actual_ship_date: "2024-06-14",
        atp_status_material_order: "Backordered",
        cdax_wo_count: 8,
        maincase_open_owner: "Chee Choong Lim",
        maincase_open_status: "Elevated to Jira",
        bookable_resource_booking_status: "Muhammad Hafiz Bin Rosli",
        bookable_resource_start_time: "2024-06-20",
        sla_count_days: 13,
        first_wo: "WO-025837528",
        aging_case_created: "60++",
        cu_reason_breakdown: "593",
        aging_case_received: "593",
        case_delay_dispatched: "0"
    },
    {
        company: "PWIT",
        case_id: "5125393699",
        work_order: "WO-026103728",
        material_order_no: "MO-704578205",
        region: "CENTRAL",
        engineer: "Chew",
        case_type: "HW Delivery",
        order_type_otc_code: "05K-Extended Warranty",
        sla: "NBD",
        multiple_visit_flag: "8",
        remark: "28/06-ADD PART",
        delay_reason_onsite: "Response Met",
        received_date: "2024-06-28",
        dispatched_date: "2024-06-28",
        response_date: "2024-07-12",
        repair_class: "IR - Incomplete Repair",
        case_status: "WO Closed",
        business_segment: "Printing",
        hpi_segment: "Commercial",
        serial_number: "MY2383W00D",
        product_no: "2RM82A",
        product_name: "HP DesignJet Z9+ Pro 64-in Printer",
        product_line: "Large Format Design HW",
        product_category_pl_code: "P3000",
        part_number: "REVISIT",
        onsite_location_city: "KUALA LUMPUR",
        customer: "FABRIC STRUCTURE",
        zip_postal_code: "53100",
        problem_case_subject: "Take up reel speed issue",
        cdax_wo_status: "Closed - Posted",
        cdax_workorder_finished_date: "2024-07-12",
        cdax_workorder_close_date: "2024-08-09",
        repair_class_codes: "IR - Incomplete Repair",
        cdax_mo_status: "Closed",
        cdax_mo_failure_code: "73 - Used & Consumed",
        backorder_etd: "2024-07-05",
        eta_aging: "Backordered",
        mo_actual_ship_date: "2024-07-05",
        atp_status_material_order: "Backordered",
        cdax_wo_count: 8,
        maincase_open_owner: "Chee Choong Lim",
        maincase_open_status: "Elevated to Jira",
        bookable_resource_booking_status: "Chew Boon Kang",
        bookable_resource_start_time: "2024-07-12",
        sla_count_days: 14,
        first_wo: "WO-026103728",
        aging_case_created: "60++",
        cu_reason_breakdown: "593",
        aging_case_received: "572",
        case_delay_dispatched: "21"
    },
    {
        company: "PWIT",
        case_id: "5125393699",
        work_order: "WO-026103728",
        material_order_no: "MO-704578205",
        region: "CENTRAL",
        engineer: "Chew",
        case_type: "HW Delivery",
        order_type_otc_code: "05K-Extended Warranty",
        sla: "NBD",
        multiple_visit_flag: "8",
        remark: "2/7-PART HOLD ... 30/7-CU REQUEST EXTEND MONITORING TILL 12/8/2024",
        delay_reason_onsite: "Part Availability",
        received_date: "2024-07-01",
        dispatched_date: "2024-07-01",
        response_date: "2024-07-12",
        repair_class: "IR - Incomplete Repair",
        case_status: "WO Closed",
        business_segment: "Printing",
        hpi_segment: "Commercial",
        serial_number: "MY2383W00D",
        product_no: "2RM82A",
        product_name: "HP DesignJet Z9+ Pro 64-in Printer",
        product_line: "Large Format Design HW",
        product_category_pl_code: "P3000",
        part_number: "2RM82-67090",
        part_description: "TUR Full Kit",
        onsite_location_city: "KUALA LUMPUR",
        customer: "FABRIC STRUCTURE",
        zip_postal_code: "53100",
        problem_case_subject: "Take up reel speed issue",
        cdax_wo_status: "Closed - Posted",
        cdax_workorder_finished_date: "2024-07-12",
        cdax_workorder_close_date: "2024-08-09",
        repair_class_codes: "IR - Incomplete Repair",
        cdax_mo_status: "Closed",
        cdax_mo_failure_code: "73 - Used & Consumed",
        backorder_etd: "2024-07-05",
        eta_aging: "Backordered",
        mo_actual_ship_date: "2024-07-05",
        atp_status_material_order: "Backordered",
        cdax_wo_count: 8,
        maincase_open_owner: "Chee Choong Lim",
        maincase_open_status: "Elevated to Jira",
        bookable_resource_booking_status: "Chew Boon Kang",
        bookable_resource_start_time: "2024-07-12",
        sla_count_days: 11,
        first_wo: "WO-026103728",
        aging_case_created: "60++",
        cu_reason_breakdown: "593",
        aging_case_received: "569",
        case_delay_dispatched: "24"
    }
]
